"""card models for seeding

Revision ID: 04d88e3b9123
Revises: 3e91ecfbd8b6
Create Date: 2023-08-08 23:55:59.564354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d88e3b9123'
down_revision = '3e91ecfbd8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isEffect', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isTuner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isFlip', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isSpirit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isUnion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isGemini', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isPendulum', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isRitual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isToon', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isFusion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isSynchro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isXYZ', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isLink', sa.Boolean(), nullable=True))
        batch_op.drop_column('ygopro_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ygopro_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('isLink')
        batch_op.drop_column('isXYZ')
        batch_op.drop_column('isSynchro')
        batch_op.drop_column('isFusion')
        batch_op.drop_column('isToon')
        batch_op.drop_column('isRitual')
        batch_op.drop_column('isPendulum')
        batch_op.drop_column('isGemini')
        batch_op.drop_column('isUnion')
        batch_op.drop_column('isSpirit')
        batch_op.drop_column('isFlip')
        batch_op.drop_column('isTuner')
        batch_op.drop_column('isEffect')

    # ### end Alembic commands ###
