"""added new validations to user

Revision ID: 3e91ecfbd8b6
Revises: 01c65dff84d4
Create Date: 2023-08-08 17:58:24.271909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e91ecfbd8b6'
down_revision = '01c65dff84d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Users_username'), type_='unique')

    # ### end Alembic commands ###
