"""added

Revision ID: 453d6fb8e3c2
Revises: a9406252cc41
Create Date: 2023-07-31 15:41:28.044371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453d6fb8e3c2'
down_revision = 'a9406252cc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
