"""models added

Revision ID: 51c004331981
Revises: 
Create Date: 2023-07-28 15:20:34.755977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c004331981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Banlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReleaseSets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('releaseDate', sa.String(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('card_race', sa.String(), nullable=True),
    sa.Column('card_attribute', sa.String(), nullable=True),
    sa.Column('card_image', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('ygopro_id', sa.Integer(), nullable=True),
    sa.Column('releasedSet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['releasedSet'], ['ReleaseSets.id'], name=op.f('fk_Cards_releasedSet_ReleaseSets')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_Decks_user_id_Users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BanlistCards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('banlist_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banlist_id'], ['Banlists.id'], name=op.f('fk_BanlistCards_banlist_id_Banlists')),
    sa.ForeignKeyConstraint(['card_id'], ['Cards.id'], name=op.f('fk_BanlistCards_card_id_Cards')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CardsinDecks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Cards.id'], name=op.f('fk_CardsinDecks_card_id_Cards')),
    sa.ForeignKeyConstraint(['deck_id'], ['Decks.id'], name=op.f('fk_CardsinDecks_deck_id_Decks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('isFirstEd', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Cards.id'], name=op.f('fk_Inventories_card_id_Cards')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_Inventories_user_id_Users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Inventories')
    op.drop_table('CardsinDecks')
    op.drop_table('BanlistCards')
    op.drop_table('Decks')
    op.drop_table('Cards')
    op.drop_table('Users')
    op.drop_table('ReleaseSets')
    op.drop_table('Banlists')
    # ### end Alembic commands ###
