"""empty message

Revision ID: 9fd93ff83c15
Revises: d75964061907
Create Date: 2023-09-26 13:40:41.951063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd93ff83c15'
down_revision = 'd75964061907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ReleaseSets', schema=None) as batch_op:
        batch_op.alter_column('set_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ReleaseSets', schema=None) as batch_op:
        batch_op.alter_column('set_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
