"""Added Column for Effects

Revision ID: c96f13e38c0f
Revises: 04d88e3b9123
Create Date: 2023-08-08 23:58:41.150116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96f13e38c0f'
down_revision = '04d88e3b9123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
