"""added set_id for card

Revision ID: d68c075f23d5
Revises: 453d6fb8e3c2
Create Date: 2023-08-01 12:24:34.985317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68c075f23d5'
down_revision = '453d6fb8e3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.drop_column('set_id')

    # ### end Alembic commands ###
