"""empty message

Revision ID: 32c0ee6c22d0
Revises: de94b440f71f
Create Date: 2023-09-20 11:34:41.822500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c0ee6c22d0'
down_revision = 'de94b440f71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
